flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/astanin/moo.git
    commit: HEAD
  extra-dep: true
extra-deps:
- gray-code-0.3.1
- monad-mersenne-random-0.1
- moo-1.0
- clustering-0.3.1
- matrices-0.4.3
resolver: lts-1.15
